---
- name: install Bigfix
  hosts: all
  become: yes
  user: ec2-user
  tasks:

  - name: Copy bfx files
    copy:
      src: /home/ec2-user/bfx-files/
      dest: /home/ec2-user/

  - name: Install bigfix
    shell: yum locallinstall /ec2-user/bfx-files/BESRelay-10.0.5.50-rhe6.x86_64.rpm