---
- name: install security tools
  hosts: all
  become: yes
  user: ec2-user
  tasks:

  - name: Fetch Rapid7 Agent
    copy:
      src: /opt/agent_installer.sh
      dest: /root/

  - name: Fetch Carbon Black 
    copy: 
      src: /opt/cb-psc-sensor-rhel-2.12.0.698755.tar 
      dest: /root/

  - name: Fetch illumio
    copy:
      src: /opt/21.2.4-7978_illumio-ven-21.2.4-7978.c8.x86_64.rpm
      dest: /root/

  - name: Add execute perm to rapid7 agent 
    shell: chmod  774 /root/agent_installer.sh

  - name: Install rapid7 Agent 
    shell: /root/agent_installer.sh install_start --token us:359e4ecd-db9f-4044-a663-b02a81058f96

  - name: untar carbon Black file
    unarchive:
      src: /root/cb-p*
      dest: /opt/
      remote_src: yes

  - name: install carbon black
    shell: /opt/carbon_black/install.sh 'WEGHPR82WV6CJFP4V#S'
  
  - name: Install illumio
    shell: yum localinstall -y /root/21.2*
    
  - name: start illumio
    shell: opt/illumio_ven/illumio-ven-ctl activate --management-server scp2.illum.io:443 --activation-code 1281d98bd9623231424e513d50b7303f4526b1e8d9feef962e3c6ce82ef9066dfdaa0e521a9053928
