---
- name: install Bigfix
  hosts: all
  become: yes
  user: ec2-user
  tasks:

  - name: copy besclient
    copy:
      src: /opt/besclient.config  
      dest: /opt

  - name: copy BigFis RPM Package  
    copy:
      src: /opt/BESAgent-10.0.5.50-rhe6.x86_64.rpm 
      dest: /home/ec2-user/

  - name: Install bigfix
    shell: yum localinstall -y /home/ec2-user/BESAgent-10.0.5.50-rhe6.x86_64.rpm 

  - name: Copy actionsite
    copy:
     src: /opt/actionsite.afxm
     dest: /etc/opt/BESClient/

  - name: start besclient
    service: 
      name: besclient 
      state: started

  - name: enable besclient 
    service: 
      name: besclient 
      enabled: yes 