---
- name: Install SSM on BigFix Servers
  hosts: all
  become: yes
  user: ec2-user
  tasks: 

  - name: Install SSM Agent on Servers
    dnf: 
      name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
      state: present 

  - name: Start SSM Agent
    service: 
      name: amazon-ssm-agent
      state: started

  - name: Enable SSM Agent
    service:
      name: amazon-ssm-agent
      state: enabled
      


   











